name: Banger and Co - Continous Integration
on:
  #execute workflow on every push to any repo or on a PR to the master.
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20 #after 20 minutes, timeout the CI process.
    steps:
      - name: Obtaining copy of repository for building.
      - uses: actions/checkout@v2 #download copy of the repo on the branch to the runner.
      - name: Set up Java JDK 8
        uses: actions/setup-java@v2 #configure the java jdk 8timeout-minutes:
        with:
          java-distributon: '8'
          distribution: 'adopt'
      - name: Build/Test With Maven
        #verify - run tests
        #batch mode - run in a non-interactive mode
        #update-snapshots - do not cache any maven dependencies.
        run: mvn verify --batch-mode --update-snapshots

